AsteOnline/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from gestione import urls
from . import views

urlpatterns = [
    # Pagine legate alla registrazione
    path('signupV/', views.VenditoreCreate.as_view(), name = 'registrazione-venditore'),
    path('signupA/', views.AcquirenteCreate.as_view(), name = 'registrazione-acquirente'),
    path('signup/', views.UtenteCreate.as_view(), name = 'registrazione'),
    
    # Pagina del login che eredita da 'auth_views'
    path("login/", auth_views.LoginView.as_view(), name="login"),
    # Pagina del logout
    path("logout/", views.LogoutView.as_view(), name="logout"),

    # Url legato all'app gestione
    path('gestione/', include('gestione.urls')),

    # Url legato alla documentazione
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # Url legato all'admin
    path('admin/', admin.site.urls),

    # Homepage
    path('', views.HomeView.as_view(), name="homepage")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestione/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'gestione'

urlpatterns = [
    # Pagine legate all'annuncio
    path('ricerca/', views.AnnuncioSearchView.as_view(), name = 'annuncio-search'),
    path('nuovo_annuncio/', views.AnnuncioCreateView.as_view(), name = 'annuncio-create'),
    path('annuncio/<int:pk>/', views.AnnuncioDetailView.as_view(), name='annuncio-detail'),
    path('annuncio/<int:pk>/update/', views.AnnuncioUpdateView.as_view(), name='annuncio-update'),
    path('annuncio/<int:pk>/delete/', views.AnnuncioDeleteView.as_view(), name='annuncio-delete'),

    # Pagina legata alla creazione di un'offerta
    path('nuova_offerta/<articolo_id>/', views.OffertaCreateView.as_view(), name='offerta-create'),

    # Pagine legate alle recensioni
    path('recensioni/<venditore_username>/', views.RecensioneListView.as_view(), name = 'recensione-list'),
    path('nuova_recensione/<venditore_username>/', views.RecensioneCreateView.as_view(), name='recensione-create'),
]

gestione/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from datetime import datetime
import string

class AnnuncioCreateForm(forms.ModelForm):
    """
    Form usato per la creazione di un annuncio per inserire un :model:'gestione/Articolo'
    """
    class Meta:
        model = Articolo
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        Sovrascrittura della funzione __init__ che viene utilizzata per riscrivere le label
        dei campi da inserire e nasconde alcune field che l'utente non deve modificare.
        """
        super().__init__(*args, **kwargs)
        self.fields['titolo'].label = "Titolo:"
        self.fields['schedaTecnica'].label = "Scheda tecnica:"
        self.fields['categoria'].label = "Categoria:"
        self.fields['immagine'].label = "Immagine:"
        self.fields['prezzoIniziale'].label = "Prezzo iniziale:"
        self.fields['durataAsta'].label = "Durata asta:"
        self.fields['dataFineAsta'].required = False
        self.fields['dataFineAsta'].widget = forms.HiddenInput()
        self.fields['terminato'].required = False
        self.fields['terminato'].widget = forms.HiddenInput()
        self.fields['venditore'].widget = forms.HiddenInput()
        self.fields['venditore'].required = False
    
    def clean_titolo(self):
        """
        Funzione che controlla che nel titolo non vengano inseriti caratteri speciali.
        """
        titolo = self.cleaned_data.get('titolo')
        # Effettua la validazione per evitare caratteri speciali
        for i in titolo:
            if i in string.punctuation:
                raise forms.ValidationError("Il titolo non può contenere caratteri speciali.")
        return titolo

    def clean_schedaTecnica(self):
        """
        Funzione che controlla che nella schede tecnica non vengano inseriti caratteri speciali.
        """
        schedaTecnica = self.cleaned_data.get('schedaTecnica')
        # Effettua la validazione per evitare caratteri speciali
        for i in schedaTecnica:
            if i in string.punctuation:
                raise forms.ValidationError("La scheda tecnica non può contenere caratteri speciali.")
        return schedaTecnica

class AnnuncioUpdateForm(forms.ModelForm):
    """
    Form usato per la modifica di alcuni campi di un annuncio e permette di modificare
    solo alcuni campi del :model:'gestione/Articolo'.
    """
    class Meta:
        model = Articolo
        fields = ('titolo', 'schedaTecnica', 'categoria')

    def __init__(self, *args, **kwargs):
        """
        Sovrascrittura della funzione __init__ che viene utilizzata per riscrivere le label
        dei campi da modificare.
        """
        super().__init__(*args, **kwargs)
        self.fields['titolo'].label = "Titolo:"
        self.fields['schedaTecnica'].label = "Scheda tecnica:"
        self.fields['categoria'].label = "Categoria:"

# Form riguardanti le offerte
class OffertaCreateForm(forms.Form):
    """
    Form usato per l'inserimento di una nuova offerta del modello :model:'gestione/Offerta'.
    """
    saldo = forms.DecimalField(label='Saldo:', max_digits=7, decimal_places=2, min_value=1)

# Form riguardanti le recensioni
class RecensioneCreateForm(forms.ModelForm):
    """
    Form usato per la creazione di una nuova recensione tramite il modello :model:'gestione/Recensione'.
    """
    class Meta:
        model = Recensione
        fields = ('testo', 'voto')

    def __init__(self, *args, **kwargs):
        """
        Sovrascrittura della funzione __init__ che viene utilizzata per riscrivere le label
        dei campi da modificare.
        """
        super().__init__(*args, **kwargs)
        self.fields['testo'].label = "Commento:"
        self.fields['voto'].label = "Voto:"

    def clean_testo(self):
        """
        Funzione che controlla che nel testo non vengano inseriti caratteri speciali.
        """
        testo = self.cleaned_data.get('testo')
        # Effettua la validazione per evitare caratteri speciali
        for i in testo:
            if i in string.punctuation:
                raise forms.ValidationError("Il testo non può contenere caratteri speciali.")
        return testo

gestione/views.py
from .models import *
from .forms import *

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import UpdateView, DeleteView, DetailView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from django.db.models import Q
from datetime import timedelta
from django.utils import timezone

# Costanti
CATEGORIE = ['Elettronica', 'Informatica', 'CD e Vinili', 'Videogiochi', 'Strumenti musicali', 'Film e DVD']

# View legate agli Annunci
class AnnuncioCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """
    CreateView usata per creare un nuovo annuncio e utilizza come modello :model:'gestione.Articolo'.

    **Template:**
    :template:'gestione/annuncio_create.html'
    """
    model = Articolo
    title = "Inserimento annuncio"
    form_class = AnnuncioCreateForm
    template_name = 'annuncio_create.html'
    success_url = reverse_lazy('homepage')

    def test_func(self):
        """
        Questa funzione è ereditata da UserPassesTestMixin che obbliga la View a 
        controllare che l'utente faccia parte del gruppo dei Venditori.
        """
        return self.request.user.groups.filter(name='Venditori').exists()

    def form_valid(self, form):
        """
        Questa funzione che viene eseguita se il form inserito è valido e sovrascrive
        il campo venditore con l'username dell'utente.
        """
        form.instance.venditore = self.request.user.username
        return super().form_valid(form)

    def form_invalid(self, form):
        """
        Questa funzione viene eseguita su il form non è corretta e viene ricaricata 
        con gli errori.
        """
        return render(self.request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        """
        Questa funzione viene effettuata con il metodo POST e FILE per permettere il 
        caricamento dell'immagine e controlla se il form è valido e poi in base a questo
        carica la giusta funzione.
        """
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.instance.venditore = self.request.user.username
            messages.success(request, "Annuncio inserito con successo.")
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AnnuncioDetailView(DetailView):
    """
    DetailView che fa vedere l'articolo e tutti i suoi dettagli legati all'asta,
    il modello è sempre :model:'gestione/Articolo'.

    **Template:**
    :template:'gestione/annuncio_detail.html'
    """
    model = Articolo
    template_name = 'annuncio_detail.html'
    context_object_name = 'articolo'

    def get_context_data(self, **kwargs):
        """
        Funzione che carica nel context i vari dati che servono al template: l'ultima offerta,
        il tempo rimanente, lo username e gli articoli consigliati.
        """
        context = super().get_context_data(**kwargs)
        articolo = self.object 

        # Ottieni l'ultima offerta per l'articolo
        ultima_offerta = Offerta.objects.filter(articolo=self.object).order_by('-id').first()
        
        # Viene ottenuto il tempo rimanente
        if str(articolo.dataFineAsta - timezone.now())[0] == '-':
            context['tempo_restante'] = 0
            articolo.terminato = True
            articolo.save()
        else:
            context['tempo_restante'] = round((articolo.dataFineAsta - timezone.now()).seconds / 60)
        context['ultima_offerta'] = ultima_offerta
        context['username'] = self.request.user.username

        # Vengono ottenuti gli articoli consigliati
        articoli_consigliati = Articolo.objects.filter(
            Q(titolo__icontains=articolo.titolo) | Q(categoria=articolo.categoria, prezzoIniziale__range=[articolo.prezzoIniziale-20, articolo.prezzoIniziale+20])
        ).exclude(id=articolo.id)[:3]
        context['articoli_consigliati'] = articoli_consigliati

        if (self.request.user.groups.filter(name='Venditori').exists()):
            context['is_venditore'] = True
        else:
            context['is_venditore'] = False
        
        return context

class AnnuncioUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    UpdateView che permette di aggiornare dei dettagli legati all'asta,
    il modello è sempre :model:'gestione/Articolo'.

    **Template:**
    :template:'gestione/annuncio_update.html'
    """
    model = Articolo
    form_class = AnnuncioUpdateForm
    template_name = 'annuncio_update.html'
    success_url = reverse_lazy('homepage')

    def test_func(self):
        """
        Funzione che controlla che l'utente che vuole modificare l'asta sia il venditore
        creatore dell'asta stessa.
        """
        articolo = self.get_object()
        return articolo.venditore == self.request.user.username

    def form_valid(self, form):
        """
        Funzione che controlla che il form sia valido e poi inserisce il messaggio dell'aggiornamento riuscito.
        """
        response = super().form_valid(form)

        messages.success(self.request, "Annuncio aggiornato correttamente.")

        return response


class AnnuncioDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    DeleteView che permette di eliminare un annuncio, il modello è 
    sempre :model:'gestione/Articolo'.

    **Template:**
    :template:'gestione/annuncio_delete.html'
    """
    model = Articolo
    template_name = 'annuncio_delete.html'
    success_url = reverse_lazy('homepage')

    def test_func(self):
        """
        Funzione che controlla che l'utente che vuole eliminare l'asta sia il venditore
        creatore dell'asta stessa.
        """
        articolo = self.get_object()
        return articolo.venditore == self.request.user.username

class AnnuncioSearchView(ListView):
    """
    ListView che permette di cercare tutti gli articoli che hanno nel titolo la parola
    che viene ricercata, il modello è sempre :model:'gestione/Articolo'.

    **Template:**
    :template:'gestione/annuncio_search.html'
    """
    model = Articolo
    template_name = 'annuncio_search.html'
    context_object_name = 'articoli'

    def get_queryset(self):
        """
        Funzione, ereditata da ListView, che viene utilizzata per ottenere la queryset.
        """
        query = self.request.GET.get('q')  # Ottiene il valore della query dalla richiesta GET
        if query:
            return Articolo.objects.filter(titolo__icontains=query)  # Filtra gli articoli per il titolo che contiene la query
        else:
            return Articolo.objects.all()  # Restituisce tutti gli articoli se la query non è presente

    def get_context_data(self, **kwargs):
        """
        Funzione che carica nel context i vari dati che servono al template e cioè il risultato
        delle query.
        """
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('q')  # Passa il valore della query al contesto del template
        return context

# View riguardanti le offerte
class OffertaCreateView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    View che viene utilizzata per fare un'offerta ad un'asta, il modello utilizzato
    è :model:'gestione/Offerta'

    **Template:**
    :template:'gestione/offerta_create.html'
    """
    def test_func(self):
        """
        Questa funzione è ereditata da UserPassesTestMixin che obbliga la View a 
        controllare che l'utente faccia parte del gruppo dei Acquirenti.
        """
        return self.request.user.groups.filter(name='Acquirenti').exists()

    def get(self, request, articolo_id):
        """
        Questa funzione è stata inserita in quanto senza di essa non so perché non funziona
        la View.
        """
        articolo = get_object_or_404(Articolo, pk=articolo_id)
        form = OffertaCreateForm()
        return render(request, 'offerta_create.html', {'form': form, 'articolo': articolo})

    def post(self, request, articolo_id):
        """
        Questa funzione viene utilizzata per il metodo POST, controlla che l'articolo esista,
        che il form sia valido e che l'offerta sia più alta dell'ultima inserita e poi la salva
        reindirizzando poi l'utente sulla pagina detail dell'annuncio.
        """
        articolo = get_object_or_404(Articolo, pk=articolo_id)
        form = OffertaCreateForm(request.POST)

        if form.is_valid():
            saldo = form.cleaned_data['saldo']
            if saldo < articolo.prezzoIniziale:
                form.add_error('saldo', 'L\'offerta deve essere maggiore dell\'offerta iniziale.')
            elif articolo.offerta_set.filter(saldo__gte=saldo).exists():
                form.add_error('saldo', 'L\'offerta deve essere maggiore di quelle già fatte.')
            else:
                offerta = Offerta(acquirente=request.user, articolo=articolo, saldo=saldo)
                offerta.save()
                messages.success(request, "Offerta inserita con successo.")
                return redirect('gestione:annuncio-detail', pk=articolo.id)

        return render(request, 'offerta_create.html', {'form': form, 'articolo': articolo})

# View riguardanti le recensioni
class RecensioneListView(ListView):
    """
    ListView che mostra le recensini di un dato venditore e anche la lista degli 
    articoli che il venditore ha in vendita, , il modello usato è quello del 
    :model:'gestione/Recensione'

    **Template:**
    :template:'gestione/recensione_list.html'
    """
    model = Recensione

gestione/templates/annuncio_create.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock %} 

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
    <h1> {{view.title}} </h1>
{% endblock %}

{% block content %} 
    <h2>Crea Annuncio:</h2>
    <form method=POST enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Aggiungi</button>

    </form>

{% endblock %}

gestione/templates/annuncio_delete.html
{% extends 'base.html' %}

{% block content %}
  <h2>Elimina Articolo</h2>
  <p>Sei sicuro di voler eliminare questo articolo?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Elimina</button>
  </form>
{% endblock %}

gestione/templates/annuncio_detail.html
{% extends 'base.html' %}

{% block title %}Dettaglio Articolo{% endblock %}

{% block content %}
  <h1>{{ articolo.titolo }}</h1>
  <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
  <p>Scheda tecnica: {{ articolo.schedaTecnica }}</p>
  <p>Prezzo iniziale: {{ articolo.prezzoIniziale }}</p>
  <p>Data di inizio asta: {{ articolo.dataInizioAsta }}</p>
  <p>Durata asta: {{ articolo.durataAsta }}</p>
  <p>Venditore: <a href="{% url 'gestione:recensione-list' venditore_username=articolo.venditore %}">{{articolo.venditore}}</a></p>

  {% if ultima_offerta %}
      <h2>Ultima Offerta</h2>
      <p>Acquirente: {{ ultima_offerta.acquirente }}</p>
      <p>Offerta: {{ ultima_offerta.saldo }}$</p>
  {% else %}
      <p>Non ci sono offerte per questo articolo al momento.</p>
  {% endif %}
  {% if user.is_authenticated %}
    {% if tempo_restante > 1 and not articolo.terminato %}
      <p>Tempo restante: {{ tempo_restante }} minuti.</p>
      {% if not is_venditore %}
        <a href="{% url 'gestione:offerta-create' articolo_id=articolo.id %}" class="btn btn-primary">Nuova Offerta</a>
      {% endif %}
    {% else %}
      <p>Asta terminata</p>
    {% endif %}
  {% endif %}

  {% if articolo.venditore == username %}
  <a href="{% url 'gestione:annuncio-update' pk=articolo.id %}" class="btn btn-primary">Modifica</a>
  <a href="{% url 'gestione:annuncio-delete' pk=articolo.id %}" class="btn btn-primary">Elimina</a>
  {% endif %}

  <h3>Articoli consigliati</h3>
  <div class="row">
    {% for articolo in articoli_consigliati %}
      {% if not articolo.terminato %}
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ articolo.titolo }}</h5>
            <p class="card-text">{{ articolo.descrizione }}</p>
            <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
            <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Dettaglio</a>
          </div>
        </div>
      </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

gestione/templates/annuncio_search.html
{% extends 'base.html' %}

{% block title %}Ricerca Articolo{% endblock %}

{% block content %}
    <h1>Ricerca Articolo</h1>

    <form method="GET" action="{% url 'gestione:annuncio-search' %}">
        <input type="text" name="q" placeholder="Cerca articolo">
        <button type="submit">Cerca</button>
    </form>

    <h2>Risultati della ricerca per "{{ search_query }}"</h2>

    {% if articoli %}
        <ul>
            {% for articolo in articoli %}
                {% if not articolo.terminato %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ articolo.titolo }}</h5>
                        <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
                        <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Vai</a>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p>Nessun articolo trovato.</p>
    {% endif %}
{% endblock %}

gestione/templates/annuncio_update.html
{% extends 'base.html' %}

{% block content %}
  <h2>Modifica Articolo</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salva</button>
  </form>
{% endblock %}

gestione/templates/createAnnuncio.html
{% block title %} {{view.title}} {% endblock %} 

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
    <h1> {{view.title}} </h1>
{% endblock %}

{% block content %} 
    <h2>Crea Annuncio:</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Aggiungi</button>

    </form>

{% endblock %}

gestione/templates/offerta_create.html
{% extends 'base.html' %}

{% block content %}
  <h2>Nuova Offerta per l'Articolo "{{ articolo.titolo }}"</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if form.errors %}
      <ul class="errorlist">
        {% for field_errors in form.errors.values %}
          {% for error in field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
        {% endfor %}
      </ul>
    {% endif %}
    <button type="submit">Invia Offerta</button>
  </form>
{% endblock %}

gestione/templates/recensione_create.html
{% extends 'base.html' %}

{% block content %}
  <h2>Nuova Recensione</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Invia Recensione</button>
  </form>
{% endblock %}

gestione/templates/recensione_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Recensioni</h1>

    <!-- Mostra le recensioni -->
    {% for recensione in recensioni %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">Recensione di {{ recensione.acquirente.username }}</h5>
                <p class="card-text">{{ recensione.testo }}</p>
                <p class="card-text">Voto: {{ recensione.voto }}/5</p>
            </div>
        </div>
    {% empty %}
        <p>Non ci sono recensioni disponibili.</p>
    {% endfor %}
    {% if not gruppo_venditore %}
        <a href="{% url 'gestione:recensione-create' venditore_username=venditore %}" class="btn btn-primary">Nuova Recensione</a>
    {% endif %}
    
  
    <hr>
    
    <h1>Articoli in vendita del venditore</h1>
  
    <!-- Mostra gli articoli in vendita -->
    {% for articolo in articoli %}
        {% if not articolo.terminato %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ articolo.titolo }}</h5>
                    <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
                    <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Vai</a>
                </div>
            </div>
        {% endif %}
    {% empty %}
        <p>Non ci sono articoli in vendita.</p>
    {% endfor %}
{% endblock %}