AsteOnline/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from gestione import urls
from . import views

urlpatterns = [
    # Pagine legate alla registrazione
    path('signupV/', views.VenditoreCreate.as_view(), name = 'registrazione-venditore'),
    path('signupA/', views.AcquirenteCreate.as_view(), name = 'registrazione-acquirente'),
    path('signup/', views.UtenteCreate.as_view(), name = 'registrazione'),
    
    # Pagina del login che eredita da 'auth_views'
    path("login/", auth_views.LoginView.as_view(), name="login"),
    # Pagina del logout
    path("logout/", views.LogoutView.as_view(), name="logout"),

    # Url legato all'app gestione
    path('gestione/', include('gestione.urls')),

    # Url legato alla documentazione
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # Url legato all'admin
    path('admin/', admin.site.urls),

    # Homepage
    path('', views.HomeView.as_view(), name="homepage")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestione/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'gestione'

urlpatterns = [
    # Pagine legate all'annuncio
    path('ricerca/', views.AnnuncioSearchView.as_view(), name = 'annuncio-search'),
    path('nuovo_annuncio/', views.AnnuncioCreateView.as_view(), name = 'annuncio-create'),
    path('annuncio/<int:pk>/', views.AnnuncioDetailView.as_view(), name='annuncio-detail'),
    path('annuncio/<int:pk>/update/', views.AnnuncioUpdateView.as_view(), name='annuncio-update'),
    path('annuncio/<int:pk>/delete/', views.AnnuncioDeleteView.as_view(), name='annuncio-delete'),

    # Pagina legata alla creazione di un'offerta
    path('nuova_offerta/<articolo_id>/', views.OffertaCreateView.as_view(), name='offerta-create'),

    # Pagine legate alle recensioni
    path('recensioni/<venditore_username>/', views.RecensioneListView.as_view(), name = 'recensione-list'),
    path('nuova_recensione/<venditore_username>/', views.RecensioneCreateView.as_view(), name='recensione-create'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    {% block head %}{% endblock %}
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'homepage' %}">AsteOnline</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gestione:annuncio-search' %}">Ricerca</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if is_venditore %}
                <!-- Se l'utente è un venditore, mostra i link per il proprio profilo e per creare un nuovo annuncio -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gestione:annuncio-create' %}">Crea annuncio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gestione:recensione-list' venditore_username=username %}">Profilo</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <!-- Se l'utente è autenticato, mostra un link per il logout -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <!-- Se l'utente non è autenticato, mostra i link per il login e la registrazione -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registrazione' %}">Registrazione</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    <!-- Contenuto principale -->
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Inclusione i file JavaScript di Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-6">
      <h2>Elettronica</h2>
      {% for articolo in articoli %}
        {% if articolo.categoria == 'Elettronica' and not articolo.terminato %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ articolo.titolo }}</h5>
              <p class="card-text">{{ articolo.schedaTecnica }}</p>
              <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
              <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Dettaglio</a>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-md-6">
      <h2>Informatica</h2>
      {% for articolo in articoli %}
        {% if articolo.categoria == 'Informatica' and not articolo.terminato %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ articolo.titolo }}</h5>
              <p class="card-text">{{ articolo.schedaTecnica }}</p>
              <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
              <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Dettaglio</a>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>CD e Vinili</h2>
      {% for articolo in articoli %}
        {% if articolo.categoria == 'CD e Vinili' and not articolo.terminato %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ articolo.titolo }}</h5>
              <p class="card-text">{{ articolo.schedaTecnica }}</p>
              <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
              <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Dettaglio</a>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-md-6">
      <h2>Videogiochi</h2>
      {% for articolo in articoli %}
        {% if articolo.categoria == 'Videogiochi' and not articolo.terminato %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ articolo.titolo }}</h5>
              <p class="card-text">{{ articolo.schedaTecnica }}</p>
              <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
              <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Dettaglio</a>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>Strumenti musicali</h2>
      {% for articolo in articoli %}
        {% if articolo.categoria == 'Strumenti musicali' and not articolo.terminato %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ articolo.titolo }}</h5>
              <p class="card-text">{{ articolo.schedaTecnica }}</p>
              <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
              <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Dettaglio</a>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-md-6">
      <h2>Film e DVD</h2>
      {% for articolo in articoli %}
        {% if articolo.categoria == 'Film e DVD' and not articolo.terminato %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ articolo.titolo }}</h5>
              <p class="card-text">{{ articolo.schedaTecnica }}</p>
              <img src="{{ articolo.immagine.url }}" alt="Immagine Annuncio" width="120"/>
              <a href="{% url 'gestione:annuncio-detail' pk=articolo.id %}" class="btn btn-primary">Dettaglio</a>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/preregistration.html
{% extends 'base.html' %}

{% block title %}Registrazione{% endblock %}

{% block content %}
<div class="container">
    <div class="box left-box">
        <h2>Registrazione Venditore</h2>
        <p>Registrati come venditore</p>
        <a href="{% url 'registrazione-venditore' %}">Registrati</a>
    </div>
    <div class="box right-box">
        <h2>Registrazione Acquirente</h2>
        <p>Registrati come acquirente</p>
        <a href="{% url 'registrazione-acquirente' %}">Registrati</a>
    </div>
</div>
{% endblock %}

<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .box {
        width: 200px;
        height: 200px;
        margin: 10px;
        padding: 20px;
        text-align: center;
    }

    .left-box {
        background-color: lightblue;
    }

    .right-box {
        background-color: lightgreen;
    }
</style>

templates/registration.html
{% extends 'base.html' %}

{% block title %} Creazione Account {% endblock title %}

{% block header1 %}
    <h1> Pagina di Registrazione </h1>
    <p> Si prega di compilare i campi necessari </p>
{% endblock header1 %}

{% block content %}
    <form method='post'> {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class="btn btn-success" value="Registrati">
    </form>
{% endblock content %}